export const RESEARCH_AI_GATEWAY = Symbol("RESEARCH_AI_GATEWAY");
export const RESEARCH_SEARCH_GATEWAY = Symbol("RESEARCH_SEARCH_GATEWAY");
export const RESEARCH_FETCH_GATEWAY = Symbol("RESEARCH_FETCH_GATEWAY");
export const RESEARCH_EXECUTION_GATEWAY = Symbol(
  "RESEARCH_EXECUTION_GATEWAY",
);
