export const SOURCE_ACQUISITION = Symbol("SOURCE_ACQUISITION");
export const SOURCE_ACQUISITION_TRANSPORT = Symbol("SOURCE_ACQUISITION_TRANSPORT");
export const SOURCE_ACQUISITION_DNS = Symbol("SOURCE_ACQUISITION_DNS");
export const SOURCE_ACQUISITION_CLOCK = Symbol("SOURCE_ACQUISITION_CLOCK");
export const SOURCE_DISCOVERY_PROVIDER = Symbol("SOURCE_DISCOVERY_PROVIDER");
