export const TELEGRAM_UPDATES_PERSISTENCE = Symbol(
  "TELEGRAM_UPDATES_PERSISTENCE",
);
export const TELEGRAM_CHECKPOINTS_PERSISTENCE = Symbol(
  "TELEGRAM_CHECKPOINTS_PERSISTENCE",
);
export const TELEGRAM_REVIEW_SESSIONS_PERSISTENCE = Symbol(
  "TELEGRAM_REVIEW_SESSIONS_PERSISTENCE",
);
