export const CURATION_DNS_LOOKUP = Symbol("CURATION_DNS_LOOKUP");
export const CURATION_HTTP = Symbol("CURATION_HTTP");
export const CURATION_SLEEP = Symbol("CURATION_SLEEP");
export const CURATION_RANDOM = Symbol("CURATION_RANDOM");
export const CURATION_STRUCTURED_GENERATION = Symbol("CURATION_STRUCTURED_GENERATION");
export const CURATION_FACT_SEARCH = Symbol("CURATION_FACT_SEARCH");
export const CURATION_STORY_DEDUPLICATION_PERSISTENCE = Symbol(
  "CURATION_STORY_DEDUPLICATION_PERSISTENCE",
);
export const CURATION_NOW = Symbol("CURATION_NOW");
export const CURATION_SEMANTIC_ATTEMPT_LIMIT = Symbol(
  "CURATION_SEMANTIC_ATTEMPT_LIMIT",
);
