export const SCHEDULER_APPLICATION = Symbol("SCHEDULER_APPLICATION");
export const SCHEDULER_NEWS_WORKFLOW_APPLICATION = Symbol(
  "SCHEDULER_NEWS_WORKFLOW_APPLICATION",
);
export const SCHEDULER_EDITORIAL_WORKFLOW_APPLICATION = Symbol(
  "SCHEDULER_EDITORIAL_WORKFLOW_APPLICATION",
);
export const SCHEDULER_PIPELINE_LEASE_APPLICATION = Symbol(
  "SCHEDULER_PIPELINE_LEASE_APPLICATION",
);
export const SCHEDULER_REVIEW_DELIVERY_APPLICATION = Symbol(
  "SCHEDULER_REVIEW_DELIVERY_APPLICATION",
);
export const SCHEDULER_AUDIT_APPLICATION = Symbol(
  "SCHEDULER_AUDIT_APPLICATION",
);
export const SCHEDULER_NOTIFICATION_APPLICATION = Symbol(
  "SCHEDULER_NOTIFICATION_APPLICATION",
);
export const SCHEDULER_ID_GENERATOR = Symbol("SCHEDULER_ID_GENERATOR");
export const SCHEDULER_CLOCK = Symbol("SCHEDULER_CLOCK");
export const SCHEDULER_TIMER = Symbol("SCHEDULER_TIMER");
