export const PIPELINE_LEASE_APPLICATION = Symbol(
  "PIPELINE_LEASE_APPLICATION",
);

export const NOTION_AUDIT_DELIVERY_APPLICATION = Symbol(
  "NOTION_AUDIT_DELIVERY_APPLICATION",
);

export const NOTION_AUDIT_GATEWAY = Symbol("NOTION_AUDIT_GATEWAY");
