export const EDITORIAL_WORKFLOW_APPLICATION = Symbol(
  "EDITORIAL_WORKFLOW_APPLICATION",
);
export const ARTICLE_PUBLISHED_EVENT_PUBLISHER = Symbol(
  "ARTICLE_PUBLISHED_EVENT_PUBLISHER",
);
export const EDITORIAL_DRAFT_GATEWAY = Symbol("EDITORIAL_DRAFT_GATEWAY");
export const EDITORIAL_PUBLICATION_GATEWAY = Symbol(
  "EDITORIAL_PUBLICATION_GATEWAY",
);
export const EXCLUDED_TOPIC_PUBLICATION_POLICY = Symbol(
  "EXCLUDED_TOPIC_PUBLICATION_POLICY",
);
