export const PUBLICATION_MILESTONES_REPOSITORY = Symbol(
  "PUBLICATION_MILESTONES_REPOSITORY",
);
export const PUBLICATION_MILESTONE_DELIVERY_GATEWAY = Symbol(
  "PUBLICATION_MILESTONE_DELIVERY_GATEWAY",
);
export const PUBLICATION_MILESTONES_OPTIONS = Symbol(
  "PUBLICATION_MILESTONES_OPTIONS",
);
