export const NEWS_SETTINGS_REPOSITORY = Symbol("NEWS_SETTINGS_REPOSITORY");
export const NEWS_FEATURE_FLAGS_REPOSITORY = Symbol(
  "NEWS_FEATURE_FLAGS_REPOSITORY",
);
export const TELEGRAM_SETTINGS_INPUT_REPOSITORY = Symbol(
  "TELEGRAM_SETTINGS_INPUT_REPOSITORY",
);
